filters:
  geos: ["Dallas, TX", "75253", "Fort Worth, TX"]
  status: ["FOR_SALE"]
  home_types: ["SINGLE_FAMILY"]
  price_min: 80000
  price_max: 400000
  beds_min: 3
  baths_min: 2
  min_sqft: 1000
  min_lot_sqft: 4000
  year_built_min: 1950
  max_dom: 30
  include_pending: false
  hoa_max: null
  price_reduction_only: false
  page_cap: 5

arv_config:
  comp_radius_mi: 0.75
  comp_window_months: 6
  extend_window_if_insufficient: 12
  min_comps: 3
  ppsf_method: median
  adjustments:
    bed_step_pct: 0.04
    bath_step_pct: 0.05
    lot_size_cap_ratio: 2.0
    age_condition_proxy: false
  confidence_method: n_iqr

profit_config:
  rehab_budget: null
  closing_costs_pct: 0.03
  selling_costs_pct: 0.06
  misc_buffer_pct: 0.02
  moe_pct_conservative: 0.10
  moe_pct_optimistic: 0.03

deal_screen:
  max_list_to_arv_pct: null

# Cache configuration - controls caching behavior for API calls and LLM requests
cache_config:
  # Clear all cache before each run (useful for fresh data)
  clear_before_run: false
  # Enable/disable LLM response caching (saves OpenAI API costs)
  llm_cache_enabled: true
  # Enable/disable Zillow API response caching (saves API calls)
  api_cache_enabled: true
  # Time-to-live for cache entries in hours
  cache_ttl_hours: 24

prompt: |
  Texas DFW single-family houses, 3+2 minimum, decent lots, DOM < 30,
  budget 80k–400k. Use nearby sold comps within 0.75mi and 6 months;
  extend to 12 months if fewer than 3 comps.

